apiVersion: v1
kind: Service
metadata:
  name: ebooks-indexer
  labels:
    app: ebooks
    tier: indexer
spec:
  type: NodePort
  ports:
    - port: 9200
      nodePort: 30051
      name: api
    - port: 9300
      nodePort: 30052
      name: cluster
  selector:
    app: ebooks
    tier: indexer
