apiVersion: v1
kind: Service
metadata:
  name: ebooks-db
  labels:
    app: ebooks
    tier: db
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30053
      name: db
  selector:
    app: ebooks
    tier: db
