apiVersion: v1
kind: Service
metadata:
  name: ebooks-cache
  labels:
    app: ebooks
    tier: cache
spec:
  type: NodePort
  ports:
    - port: 6379
      nodePort: 30054
      name: cache
  selector:
    app: ebooks
    tier: cache
