apiVersion: v1
kind: Service
metadata:
  name: ebooks-frontend
  labels:
    app: ebooks
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30050
  selector:
    app: ebooks
    tier: frontend
